title: "圏論勉強ノート"
summary: |-
  圏論を勉強したメモ書きです。
  勉強を進めるにつれてページが増えていきます。

  数学的な厳密さを欠いた議論や証明を省いた部分が多くあるので、これを使って勉強するのはおすすめしません。

  教科書はSteve AwodeyのCategory Theoryを使っています。
  集合論の教科書として松坂和夫先生の集合・位相入門を使っています。

topics:
  - "haskell"
  - "圏論"
published: true
price: 0
toc_depth: 2
allow_override: true
chapters:
  - "category"
  - "commutative-diagram"
  - "largeness-of-categories"
  - "category-examples"
  - "aab586"
  - "opposite-categories"
  - "functor"
  - "full-and-faithful-functors"
  - "category-of-small-categories"
  - "823439"
  - "comma-category"
  - "slice-category"
  - "natural-isomorphism"
  - "fa185d"
  - "horizontal-composition"
  - "identity_natural_transformation"
  - "equivalence-of-categories"
  - "adjoint-functors1"
  - "category-of-functors"
  - "e38d71"
  - "product-category"
  - "b03846"
  - "hom-functor"
  - "adjoint-functors2"
  - "diagram-and-index-category"
  - "universal-mapping-property"
  - "product"
  - "limit"
  - "adjoint-functor3"
  - "pullback"
  - "monic-and-epic-morphisms"
  - "equaliser"
  - "coequaliser"
  - "complete"
  - "limit-as-equaliser"
  - "representable-functor"
  - "c03a0f"
  - "yoneda-lemma"
  - "yoneda-embedding"
  - "monoidal-category"
  - "fedfeb"
  - "kan-extension"
