title: "圏論勉強ノート"
summary: |-
  圏論を勉強したメモ書きです。
  勉強を進めるにつれてページが増えていきます。

  数学的な厳密さを欠いた議論や証明を省いた部分が多くあるので、これを使って勉強するのはおすすめしません。

  教科書はSteve AwodeyのCategory Theoryを使っています。
  集合論の教科書として松坂和夫先生の集合・位相入門を使っています。

topics:
  - "haskell"
  - "圏論"
published: true
price: 0
toc_depth: 2
allow_override: true
chapters:
  - "83e92b"
  - "2a688b"
  - "54f2b1"
  - "5aad91"
  - "aab586"
  - "66b209"
  - "91e65c"
  - "59c449"
  - "823439"
  - "9465d3"
  - "fa185d"
  - "0f4e84"
  - "09dfda"
  - "16aece"
  - "142f1a"
  - "e38d71"
  - "3c72fb"
  - "b03846"
  - "e7ba03"
  - "60fb97"
  - "179242"
  - "35b289"
  - "3e053e"
  - "954f1b"
  - "57834d"
  - "0eebe1"
  - "82db73"
  - "7d35d8"
  - "8cba84"
  - "26c6fb"
  - "88d11d"
  - "0c2fae"
  - "c03a0f"
  - "30c3f5"
  - "7c5bc2"
  - "fedfeb"
  - "kan-extension"
